'use strict';

export const TRY_LOGIN = 'TRY_LOGIN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGIN = [TRY_LOGIN, LOGIN_SUCCESS, LOGIN_FAILURE];

export const FETCH_STACKOWERFLOW = 'FETCH_STACKOWERFLOW';
export const FETCH_STACKOWERFLOW_FAILURE = 'FETCH_STACKOWERFLOW_FAILURE';
export const FETCH_STACKOWERFLOW_SUCCESS = 'FETCH_STACKOWERFLOW_SUCCESS';

export const LOGOUT = "LOGOUT";
