
const TRY_LOGIN = 'TRY_LOGIN';
const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
const LOGIN_FAILURE = 'LOGIN_FAILURE';
const LOGIN = [TRY_LOGIN, LOGIN_SUCCESS, LOGIN_FAILURE];

const LIST_STACKOWERFLOW = 'LIST_STACKOWERFLOW';

const LOGOUT = "LOGOUT";
